-- Consulta de referência (Power BI) que revelou o gateway WSGETDATA do Protheus.
-- NÃO é a consulta da rotina de EPI — arquivada só como exemplo do gateway (pedidos de compra).
-- Enviada como corpo (text/plain) no POST /rest/WSGETDATA/v1.
SELECT
    C7_FILIAL   AS 'FILIAL',
    C7_NUM      AS 'N.PC',
    C7_EMISSAO  AS 'DATADOPEDIDO',
    C7_TOTAL    AS 'VALOR',
    D1_DOC      AS 'NF',
    C7_PRODUTO  AS 'CODPRODUTO',
    C7_DESCRI   AS 'DESCRICAO',
    C7_CC       AS 'CENTRODECUSTO',
    CTT_DESC01  AS 'NOMECENTRODECUSTO',
    C7_FORNECE  AS 'FORNECEDOR',
    A2_NOME     AS 'NOMEFORNECEDOR',
    C7_DATPRF   AS 'DATADEENTREGA',
    C7_USER     AS 'CODUSUARIO',
    USR_NOME    AS 'NOMEUSUARIO',
    C7_RESIDUO  AS 'RESIDUO',
    C7_COND     AS 'CONDPAGAMENTO',
    C7_XDTVCT   AS 'VENCIMENTO',
    C7_CONTA    AS 'CONTA',
    CASE
        WHEN C7_QUJE='0' AND C7_QTDACLA='0' AND LTRIM(RTRIM(C7_RESIDUO))='' AND LTRIM(RTRIM(C7_CONTRA))='' AND C7_CONAPRO<>'B' THEN 'Verde'
        WHEN C7_QUJE='0' AND C7_QUJE<C7_QUANT AND LTRIM(RTRIM(C7_RESIDUO))='' AND LTRIM(RTRIM(C7_CONTRA))='' AND C7_CONAPRO<>'B' THEN 'Amarelo'
        WHEN C7_QUJE>=C7_QUANT AND LTRIM(RTRIM(C7_RESIDUO))='' AND LTRIM(RTRIM(C7_CONTRA))='' AND C7_CONAPRO<>'B' THEN 'Vermelho'
        WHEN C7_QTDACLA >0 AND LTRIM(RTRIM(C7_RESIDUO))='' AND LTRIM(RTRIM(C7_CONTRA))='' AND C7_CONAPRO<>'B' THEN 'Laranja'
        WHEN C7_ACCPROC<>'1' AND C7_CONAPRO='B' AND C7_QUJE < C7_QUANT AND LTRIM(RTRIM(C7_RESIDUO))='' THEN 'Azul'
        WHEN LTRIM(RTRIM(C7_CONTRA))='' AND LTRIM(RTRIM(C7_RESIDUO))='' THEN 'BRANCO'
        WHEN LTRIM(RTRIM(C7_RESIDUO))='' THEN 'CINZA'
        ELSE ''
    END AS C7_STATUS
FROM SC7010 SC7
    LEFT JOIN SD1010 SD1 ON
        C7_FILIAL = D1_FILIAL AND C7_NUM = D1_PEDIDO AND C7_ITEM = D1_ITEMPC AND
        C7_FORNECE = D1_FORNECE AND C7_LOJA = D1_LOJA AND
        LTRIM(RTRIM(D1_COD))<>'' AND SD1.D_E_L_E_T_<>'*'
    LEFT JOIN SA2010 SA2 ON
        A2_COD = C7_FORNECE AND A2_LOJA = C7_LOJA AND SA2.D_E_L_E_T_<>'*'
    LEFT JOIN CTT010 CTT ON
        CTT_CUSTO = C7_CC AND CTT.D_E_L_E_T_<>'*'
    LEFT JOIN SYS_USR SYS ON
        USR_ID = C7_USER AND SYS.D_E_L_E_T_<>'*'
WHERE SC7.D_E_L_E_T_<>'*'
